server:
  port: 9000
spring:
  application:
    name: SCW-ORDER
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.188.130
    port: 6379
    password: 123456
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/order/mapper/*.xml
eureka:
  instance:
    prefer-ip-address: true
    appname: SCW-ORDER
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
